---
# install coreutils

- block:
  # - name: update homebrew
    # homebrew: update_homebrew=yes

  - name: install coreutils
    homebrew:
      name: "{{ item }}"
      state: "{{ install_state }}"
      install_options: "{{ item }}"
    with_items: "{{ coreutils_name }}"
    tags: install
  tags:
    - bootstrap
    - update
