---
# tasks file for coreutils

- name: setup | install
  include: install.yml
  when: ansible_distribution == 'MacOSX'

- name: setup | configure
  include: coreutils.yml
  when: ansible_distribution == 'MacOSX'
