---

#####=== install ===#####

- name: install
  homebrew:
    name: "{{ coreutils_name }}"
    state: "{{ coreutils_install_state }}"
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - bootstrap_coreutils
    - install
    - install_coreutils

#####=== configure ===#####

- name: setup | determine homebrew prefix
  command: "brew --prefix"
  register: brew_prefix
  when: ansible_distribution == 'MacOSX'

- block:
  - name: bash/zsh | configure | PATH
    blockinfile:
      dest: "{{ item.profile }}"
      state: "{{ item.state }}"
      create: yes
      backup: no
      marker: "{{ coreutils_marker }}"
      block: |
        coreutils_path="{{ brew_prefix.stdout }}/opt/coreutils/libexec/gnubin"
        if [[ "$PATH" != *$coreutils_path* ]]; then
          export PATH="$coreutils_path:$PATH"
        fi
        coreutils_manpath="{{ brew_prefix.stdout }}/opt/coreutils/libexec/gnuman"
        if [[ "$PATH" != *$coreutils_manpath* ]]; then
          export PATH="$coreutils_manpath::$PATH"
        fi
    with_items:
      - "{{ coreutils_bash_configuration }}"
      - "{{ coreutils_zsh_configuration }}"
  when: >
    (ansible_distribution == 'MacOSX') and 
    (coreutils_should_override == true)
  tags:
    - bash
    - zsh
    - bootstrap
    - bootstrap_coreutils
    - configure
    - configure_coreutils
    - update
    - update_coreutils

# TODO: add unconfiguring fish...
- block:
  - name: fish | configure | PATH
    command: fish -c "set -Ux fish_user_paths {{ brew_prefix.stdout }}/opt/coreutils/libexec/gnubin"
    # trailing ':' is important; see https://github.com/fish-shell/fish-shell/issues/2090
  - name: fish | configure | MANPATH
    command: fish -c "set -Ux MANPATH '{{ brew_prefix.stdout }}/opt/coreutils/libexec/gnubin:'"
  when: >
    (ansible_distribution == 'MacOSX') and 
    (coreutils_fish_configuration.state == 'present') and 
    (coreutils_should_override == true)
  tags:
    - fish
    - bootstrap
    - bootstrap_coreutils
    - configure
    - configure_coreutils
    - update
    - update_coreutils
