---

#####=== install ===#####

- name: install
  homebrew:
    name: "{{ coreutils_name }}"
    state: "{{ install_state }}"
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - install

#####=== configure ===#####

- name: setup | determine homebrew prefix
  command: "brew --prefix"
  register: brew_prefix
  when: ansible_distribution == 'MacOSX'

- block:
  - name: bash/zsh | configure | pathmunge shell function
    blockinfile:
      dest: "{{ shell_profile }}"
      create: yes
      backup: yes
      state: present
      insertbefore: BOF
      marker: "#####=== {mark} Ansible managed pathmunge ===#####"
      # FIXME: "{{ item }}" is not expanding in block for blockinfile
      block: |
        #!/usr/bin/env {{ ansible_user_shell_name }}

        pathmunge () {
          case ":${PATH}:" in
            *:"$1":*)
              ;;
            *)
              if [ "$2" = "after" ] ; then
                PATH=$PATH:$1
              else
                PATH=$1:$PATH
              fi
          esac
        }

        manpathmunge () {
          case ":${MANPATH}:" in
            *:"$1":*)
              ;;
            *)
              if [ "$2" = "after" ] ; then
                MANPATH=$MANPATH:$1
              else
                MANPATH=$1:$MANPATH
              fi
          esac
        }

  - name: bash/zsh | configure | PATH
    blockinfile:
      dest: "{{ shell_profile }}"
      state: "{{ configuration_state }}"
      create: yes
      backup: no
      marker: "{{ coreutils_marker }}"
      block: |
        pathmunge "{{ brew_prefix.stdout }}/opt/coreutils/libexec/gnubin"
        manpathmunge "{{ brew_prefix.stdout }}/opt/coreutils/libexec/gnuman"
        export PATH=$PATH
        export MANPATH=$MANPATH
  when: ansible_distribution == 'MacOSX'
  tags:
    - bootstrap
    - configure
    - update

- block:
  - name: fish | configure | PATH
    command: fish -c "set -Ux fish_user_paths {{ brew_prefix.stdout }}/opt/coreutils/libexec/gnubin $fish_user_paths"
    # trailing ':' is important; see https://github.com/fish-shell/fish-shell/issues/2090
  - name: fish | configure | MANPATH
    command: fish -c "set -Ux MANPATH '{{ brew_prefix.stdout }}/opt/coreutils/libexec/gnubin:'"
  when: (ansible_distribution == 'MacOSX') and (ansible_user_shell | match(".*\/fish"))
  tags:
    - bootstrap
    - configure
    - update
